pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        AWS_ACCOUNT_ID = '098588167308'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
    
    stage('Terraform Init') {
            steps {
                script {
                    sh 'terraform init'
                }
            }
        }

    stage('Terraform Destroy') {
            steps {
                script {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}
